name: Linux (cabal)

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/cabal.yml'
  pull_request:
    paths:
    - 'src/**'
    - '.github/workflows/cabal.yml'

jobs:
  Ubuntu-x86_64:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        # - ubuntu-16.04
        - ubuntu-18.04
        # - ubuntu-20.04
        agda-ver:
        - 'v2.6.1'
        # - master

    env:
      AGDA_SRC: './agda-src'
      AGDA_DIST: './agda-prebuilt'

    steps:
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install ghc cabal-install alex happy

    - name: Update cabal
      run: cabal update

    - uses: actions/checkout@v2.3.2
      with:
        repository: agda/agda
        ref: ${{ matrix.agda-ver }}
        path: ${{ env.AGDA_SRC }}

    - name: Summarize the environment
      working-directory: ${{ env.AGDA_SRC }}
      run: |
        export AGDA_VERSION=$(cabal info . | head -n 1 | cut -d " " -f 2 | cut -d "-" -f 2)
        _GHC_STR=$(ghc --version)
        _CABAL_STR=$(cabal --version)
        _CACHE_KEY=$(echo "$_GHC_STR-$_CABAL_STR" | sed "s/[^a-z0-9]/_/gi")
        echo "::set-env name=AGDA_CACHE_KEY::$_CACHE_KEY"
        echo "::set-env name=AGDA_DATADIR_DEST::.agda-$AGDA_VERSION"
        echo "*** GHC version ***"     && ghc --version
        echo "*** cabal version ***"   && cabal --version
        echo "*** Agda version ***"    && echo $AGDA_VERSION

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: "~/.cabal"
        key: ${{ runner.os }}-cabal-${{ env.AGDA_CACHE_KEY }}-${{ hashFiles('**/plan.json') }}


    - name: Edit the cabal file
      working-directory: ${{ env.AGDA_SRC }}
      run: |
        sed -i '/^executable agda$/a\  ld-options: -static' Agda.cabal

    - name: Install dependencies
      working-directory: ${{ env.AGDA_SRC }}
      run: |
        cabal install --only-dependencies

    - name: Configure Agda
      working-directory: ${{ env.AGDA_SRC }}
      run: |
        cabal configure --prefix=/usr/local \
        --disable-executable-dynamic \
        --disable-shared \
        --enable-library-stripping \
        --enable-executable-stripping \
        --ghc-option=-fPIC

    - name: Build Agda
      working-directory: ${{ env.AGDA_SRC }}
      run: cabal build -j8

    - name: Produce Artifact
      working-directory: ${{ env.AGDA_SRC }}
      run: |
        mkdir $GITHUB_WORKSPACE/$AGDA_DIST
        cp -r $HOME/.cabal/share $GITHUB_WORKSPACE/$AGDA_DIST
        if [ -d "dist-newstyle" ]; then
          cp dist-newstyle/build/x86_64-*/ghc-*/*/*/*/agda $GITHUB_WORKSPACE/$AGDA_DIST
        else
          echo "::warning ::Copying agda binary in the old-style dist folder"
          cp dist/build/agda/agda $GITHUB_WORKSPACE/$AGDA_DIST
        fi

    - name: Test Agda (dummy)
      working-directory: ${{ env.AGDA_DIST }}
      run: |
        # TODO: test if the file is indeed static
        file ./agda

    - uses: actions/upload-artifact@v2
      with:
        name: agda-prebuilt
        path: ${{ env.AGDA_DIST }}

    - name: Clean up
      working-directory: ${{ env.AGDA_SRC }}
      run: cabal clean
