name: Linux (cabal)

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/cabal.yml'
  pull_request:
    paths:
    - 'src/**'
    - '.github/workflows/cabal.yml'

jobs:
  'Ubuntu (x86_64)':
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        # - ubuntu-16.04
        - ubuntu-18.04
        # - ubuntu-20.04
        agda-ver:
        - '2.6.1'
        # - master

    steps:
    - name: Setup environment
      run: |
      sudo apt install cabal-install
      cabal update

    - name: Checkout Agda repo
      uses: actions/checkout@v2.3.1
      repository: agda/agda
      ref: ${{ matrix.agda-ver }}
      path: './agda-src'

    - name: Summary of environment
      run: |
      echo "*** GHC version ***"     && ghc     --version
      echo "*** cabal version ***"   && cabal   --version

    - name: Configure (static) agda
      run: |
        cd agda-src
        sed -i '/^executable agda$/a\  ld-options: -static' Agda.cabal
        cabal configure --datadir=~/.agda-${{ matrix.agda-ver }}
        cabal build --only-dependencies

    - name: Build Agda
      run: |
        cabal build

    - name: Produce Artifact
      run: |
        mkdir $GITHUB_WORKSPACE/agda-prebuilt
        pushd $HOME/.cabal/share/x86_64-*
        cp Agda* $GITHUB_WORKSPACE/agda-prebuilt
        popd
        cp agda-src/dist-newstyle/build/x86_64-*/ghc-*/*/*/*/agda $GITHUB_WORKSPACE/agda-prebuilt
        tar

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
        with:
          name: agda-prebuilt
          path: agda-prebuilt/
